export { Header } from './Header'
export { NextHead } from './NextHead'
export { Landing } from './Landing'
export { About } from './About'
export { Services } from './Services'
export { Contact } from './Contact'
export { Footer } from './Footer'